name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go

      # actions para o docker realizar o build através do github
      # o name é apenas uma pequena descrição do passo
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login na conta Docker Hub para dar upush na imagem gerada
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # o id é usado abaixo para pegar o resultado dessa action 
      # e utiliza-lo em outro step
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # push = true e tag são utilizados para subir a imgaem no dockerhub
          # na tag será o nome da imagem
          push: true
          tags: lalausan/fv3.0-ci-go:latest


